Repository kymckay/f21as-project, pull requests merged in 2021-02, with the labels that each got.

#21 Implement Enumerated Types
  src/main/java/sim/coffee/Colour.java
  src/main/java/sim/coffee/DietaryClass.java
  src/main/java/sim/coffee/Label.java
  src/main/java/sim/coffee/Milk.java
  src/main/java/sim/coffee/Size.java
Labels: category|menu, category|orders

#23 Order class
  src/main/java/sim/coffee/Order.java
  src/main/java/sim/coffee/OrderItem.java
  src/test/java/sim/coffee/OrderTest.java
Labels: category|orders

#25 Implement OrderItem subclasses
  src/main/java/sim/coffee/OrderBeverages.java
  src/main/java/sim/coffee/OrderFood.java
  src/main/java/sim/coffee/OrderItem.java
  src/main/java/sim/coffee/OrderMerchandise.java
Labels: category|orders

#27 Commit MenuItem and related classes.
  src/main/java/sim/coffee/Beverage.java
  src/main/java/sim/coffee/Food.java
  src/main/java/sim/coffee/IllegalIDException.java
  src/main/java/sim/coffee/Menu.java
  src/main/java/sim/coffee/MenuItem.java
  src/main/java/sim/coffee/Merchandise.java
Labels: category|menu

#29 Implement the order list structure
  src/main/java/sim/coffee/Menu.java
  src/main/java/sim/coffee/OrderBeverage.java
  src/main/java/sim/coffee/OrderFood.java
  src/main/java/sim/coffee/OrderItem.java
  src/main/java/sim/coffee/OrderList.java
  src/main/java/sim/coffee/OrderMerchandise.java
Labels: category|orders

#34 Implement our GUI and initial output report
  .gitignore
  data/menu.csv
  data/orders.csv
  data/test/menu.csv
  data/test/orders.csv
  src/main/java/sim/coffee/App.java
  src/main/java/sim/coffee/BasketTableModel.java
  src/main/java/sim/coffee/Beverage.java
  src/main/java/sim/coffee/ControlsBeverage.java
  src/main/java/sim/coffee/ControlsMerchandise.java
  src/main/java/sim/coffee/CustomerGUI.java
  src/main/java/sim/coffee/DietaryClass.java
  src/main/java/sim/coffee/Food.java
  src/main/java/sim/coffee/IllegalIDException.java
  src/main/java/sim/coffee/Manager.java
  src/main/java/sim/coffee/Menu.java
  src/main/java/sim/coffee/MenuItem.java
  src/main/java/sim/coffee/MenuListSelectionModel.java
  src/main/java/sim/coffee/MenuTableModel.java
  src/main/java/sim/coffee/Merchandise.java
  src/main/java/sim/coffee/Order.java
  src/main/java/sim/coffee/OrderBasket.java
  src/main/java/sim/coffee/OrderBeverage.java
  src/main/java/sim/coffee/OrderFood.java
  src/main/java/sim/coffee/OrderItem.java
  src/main/java/sim/coffee/OrderList.java
  src/main/java/sim/coffee/OrderMerchandise.java
  src/test/java/sim/coffee/AppTest.java
  src/test/java/sim/coffee/BasketTableModelTest.java
  src/test/java/sim/coffee/IllegalIDExceptionTest.java
  src/test/java/sim/coffee/MenuTableModelTest.java
  src/test/java/sim/coffee/OrderBasketTest.java
  src/test/java/sim/coffee/OrderTest.java
Labels: category|gui, category|orders, category|tests

#35 Fix discount 2 when multiple pairs are present
  src/main/java/sim/coffee/OrderBasket.java
  src/test/java/sim/coffee/OrderBasketTest.java
Labels: category|orders
