Repository kymckay/f21as-project, pull requests merged in 2021-03, with the labels that each got.

#36 Fix issue with empty csv columns in order input
  data/orders.csv
  src/main/java/sim/coffee/Menu.java
  src/main/java/sim/coffee/Order.java
  src/main/java/sim/coffee/OrderList.java
  src/test/java/sim/coffee/OrderListTest.java
  src/test/java/sim/coffee/OrderTest.java
Labels: category|orders

#41 Reintroduced cumulative income form all orders feature
  src/main/java/sim/coffee/OrderBasket.java
Labels: type|bug

#42 Remove test dependency on Menu
  src/test/java/sim/coffee/OrderListTest.java
Labels: category|tests

#43 Fix handling of repeating decimals for display
  src/main/java/sim/coffee/BasketTableModel.java
  src/main/java/sim/coffee/Order.java
Labels: category|gui, category|orders

#47 Move item tally increase to checkout
  src/main/java/sim/coffee/OrderBasket.java
  src/test/java/sim/coffee/OrderBasketTest.java
Labels: category|orders, category|tests

#49 Clean up GUI and output strings
  src/main/java/sim/coffee/BasketTableModel.java
  src/main/java/sim/coffee/CustomerGUI.java
  src/main/java/sim/coffee/OrderBasket.java
Labels: category|gui

#50 Use a StringBuilder to create the output report
  src/main/java/sim/coffee/OrderBasket.java
Labels: category|menu, category|orders, type|optimization

#52 Fix permutation price not being applied
  src/main/java/sim/coffee/ControlsBeverage.java
  src/main/java/sim/coffee/ControlsMerchandise.java
  src/main/java/sim/coffee/CustomerGUI.java
Labels: category|gui, category|orders

#54 Fix price scaling when limited sizes available
  src/main/java/sim/coffee/Beverage.java
Labels: category|menu

#67 Implement initial Producer class
  src/main/java/sim/coffee/Manager.java
  src/main/java/sim/coffee/OrderList.java
  src/main/java/sim/coffee/Producer.java
  src/main/java/sim/coffee/Server.java
  src/main/java/sim/coffee/SharedQueue.java
  src/test/java/sim/coffee/MenuTest.java
  src/test/java/sim/coffee/OrderListTest.java
Labels: category/simulation

#68 Fix issues with arrays produced
  src/main/java/sim/coffee/Producer.java
Labels: category/orders, category/simulation

#63 Implemented staff branch
  src/main/java/sim/coffee/Server.java
  src/main/java/sim/coffee/SharedQueue.java
Labels: category/simulation

#79 Implement GUI
  src/main/java/sim/coffee/Kitchen.java
  src/main/java/sim/coffee/KitchenGUI.java
  src/main/java/sim/coffee/KitchenQueueGUI.java
  src/main/java/sim/coffee/Logger.java
  src/main/java/sim/coffee/Manager.java
  src/main/java/sim/coffee/Observer.java
  src/main/java/sim/coffee/QueueType.java
  src/main/java/sim/coffee/Server.java
  src/main/java/sim/coffee/ServerGUI.java
  src/main/java/sim/coffee/SharedQueue.java
  src/main/java/sim/coffee/SimulationGUI.java
  src/main/java/sim/coffee/Subject.java
Labels: category/gui, category/simulation

#89 Structure MVC classes into appropriate packages
  pom.xml
  src/main/java/sim/app/Manager.java
  src/main/java/sim/app/Order.java
  src/main/java/sim/app/OrderBasket.java
  src/main/java/sim/app/OrderItem.java
  src/main/java/sim/app/OrderList.java
  src/main/java/sim/coffee/BasketTableModel.java
  src/main/java/sim/coffee/CustomerGUI.java
  src/main/java/sim/coffee/Manager.java
  src/main/java/sim/coffee/MenuItem.java
  src/main/java/sim/model/Kitchen.java
  src/main/java/sim/model/Logger.java
  src/main/java/sim/model/Producer.java
  src/main/java/sim/model/QueueType.java
  src/main/java/sim/model/Server.java
  src/main/java/sim/model/SharedQueue.java
  src/main/java/sim/model/Subject.java
  src/main/java/sim/view/KitchenGUI.java
  src/main/java/sim/view/KitchenQueueGUI.java
  src/main/java/sim/view/Observer.java
  src/main/java/sim/view/ServerGUI.java
  src/main/java/sim/view/SimulationGUI.java
  src/test/java/sim/coffee/BasketTableModelTest.java
  src/test/java/sim/coffee/IllegalIDExceptionTest.java
  src/test/java/sim/coffee/MenuTableModelTest.java
  src/test/java/sim/coffee/MenuTest.java
  src/test/java/sim/coffee/OrderBasketTest.java
  src/test/java/sim/coffee/OrderListTest.java
  src/test/java/sim/coffee/OrderTest.java
Labels: category/simulation

#90 Introduce CoffeeShop class
  src/main/java/sim/app/Manager.java
  src/main/java/sim/model/CoffeeShop.java
  src/main/java/sim/model/Server.java
  src/main/java/sim/model/Subject.java
  src/main/java/sim/view/Observer.java
  src/main/java/sim/view/ServerGUI.java
  src/main/java/sim/view/SimulationGUI.java
Labels: category/simulation

#91 Fix producer not adding final order
  src/main/java/sim/model/Producer.java
Labels: category/simulation

#94 Implement serving speed controls
  src/main/java/sim/controller/SpeedController.java
  src/main/java/sim/model/Server.java
  src/main/java/sim/view/ServerGUI.java
  src/main/java/sim/view/SimulationGUI.java
Labels: category/gui, category/simulation

#97 Refactor code to better fit MVC pattern
  src/main/java/sim/app/Manager.java
  src/main/java/sim/app/Simulation.java
  src/main/java/sim/controller/SpeedController.java
  src/main/java/sim/controllers/SpeedController.java
  src/main/java/sim/interfaces/Observer.java
  src/main/java/sim/interfaces/Subject.java
  src/main/java/sim/model/CoffeeShop.java
  src/main/java/sim/model/Kitchen.java
  src/main/java/sim/model/Server.java
  src/main/java/sim/model/SharedQueue.java
  src/main/java/sim/views/KitchenGUI.java
  src/main/java/sim/views/KitchenQueueGUI.java
  src/main/java/sim/views/ServerGUI.java
  src/main/java/sim/views/SimulationGUI.java
Labels: category/simulation

#92 Write report at end of simulation
  src/main/java/sim/app/ReportWriter.java
  src/main/java/sim/model/CoffeeShop.java
  src/main/java/sim/model/Kitchen.java
  src/main/java/sim/model/Server.java
Labels: category/simulation

#104 Reuse queue view and show priority queue
  src/main/java/sim/model/CoffeeShop.java
  src/main/java/sim/model/SharedQueue.java
  src/main/java/sim/views/KitchenQueueGUI.java
  src/main/java/sim/views/QueueGUI.java
  src/main/java/sim/views/SimulationGUI.java
Labels: category/simulation

#105 Adapt data structures to fit stage 2 context
  data/menu.csv
  data/orders.csv
  src/main/java/sim/app/Order.java
  src/main/java/sim/app/OrderBasket.java
  src/main/java/sim/app/OrderItem.java
  src/main/java/sim/app/OrderList.java
  src/main/java/sim/app/ReportWriter.java
  src/main/java/sim/app/Simulation.java
  src/main/java/sim/coffee/BasketTableModel.java
  src/main/java/sim/coffee/Beverage.java
  src/main/java/sim/coffee/Colour.java
  src/main/java/sim/coffee/ControlsBeverage.java
  src/main/java/sim/coffee/ControlsMerchandise.java
  src/main/java/sim/coffee/CustomerGUI.java
  src/main/java/sim/coffee/DietaryClass.java
  src/main/java/sim/coffee/Food.java
  src/main/java/sim/coffee/IllegalIDException.java
  src/main/java/sim/coffee/Label.java
  src/main/java/sim/coffee/Menu.java
  src/main/java/sim/coffee/MenuListSelectionModel.java
  src/main/java/sim/coffee/MenuTableModel.java
  src/main/java/sim/coffee/Merchandise.java
  src/main/java/sim/coffee/Milk.java
  src/main/java/sim/coffee/Size.java
  src/main/java/sim/model/CoffeeShop.java
  src/main/java/sim/model/Customer.java
  src/main/java/sim/model/Kitchen.java
  src/main/java/sim/model/Logger.java
  src/main/java/sim/model/Menu.java
  src/main/java/sim/model/MenuItem.java
  src/main/java/sim/model/Producer.java
  src/main/java/sim/model/Server.java
  src/main/java/sim/model/SharedQueue.java
  src/main/java/sim/views/KitchenGUI.java
  src/main/java/sim/views/QueueGUI.java
  src/main/java/sim/views/ServerGUI.java
  src/test/java/sim/coffee/BasketTableModelTest.java
  src/test/java/sim/coffee/IllegalIDExceptionTest.java
  src/test/java/sim/coffee/MenuTableModelTest.java
  src/test/java/sim/coffee/MenuTest.java
  src/test/java/sim/coffee/OrderBasketTest.java
  src/test/java/sim/coffee/OrderListTest.java
  src/test/java/sim/coffee/OrderTest.java
Labels: category/orders, category/simulation, priority/high

#108 Add message dialog at the end if simulation
  src/main/java/sim/views/KitchenGUI.java
  src/main/java/sim/views/QueueGUI.java
  src/main/java/sim/views/ServerGUI.java
  src/main/java/sim/views/SimulationGUI.java
Labels: category/gui

#111 Make singleton lazy-loading thread safe
  src/main/java/sim/model/Logger.java
Labels: category/simulation

#109 Fix possibility for threads to wait indefinitely
  src/main/java/sim/model/Kitchen.java
  src/main/java/sim/model/Server.java
  src/main/java/sim/model/SharedQueue.java
  src/main/java/sim/views/KitchenGUI.java
  src/main/java/sim/views/ServerGUI.java
Labels: category/simulation

#113 Improve thread handling of SharedQueue
  src/main/java/sim/model/Kitchen.java
  src/main/java/sim/model/Server.java
  src/main/java/sim/model/SharedQueue.java
Labels: category/simulation

#115 Add EditorConfig file for consistency
  .editorconfig
Labels: category/docs

#116 Simplify logger and improve logged events
  src/main/java/sim/model/CoffeeShop.java
  src/main/java/sim/model/Kitchen.java
  src/main/java/sim/model/Logger.java
  src/main/java/sim/model/Producer.java
  src/main/java/sim/model/QueueType.java
  src/main/java/sim/model/Server.java
  src/main/java/sim/model/SharedQueue.java
  src/main/java/sim/views/ServerGUI.java
Labels: category/simulation, type/optimization

#117 Fix outstanding issues with shared objects
  data/orders.csv
  src/main/java/sim/model/CoffeeShop.java
  src/main/java/sim/model/Kitchen.java
  src/main/java/sim/model/Producer.java
  src/main/java/sim/model/Server.java
  src/main/java/sim/model/SharedQueue.java
  src/main/java/sim/views/QueueLaneGUI.java
  src/main/java/sim/views/ServerGUI.java
  src/main/java/sim/views/SimulationGUI.java
Labels: category/simulation
